import type { Metadata } from "next";
import "./globals.css";
import EmotionCSSRegistry from "@/lib/EmotionCSSRegistry";
import {Inter} from "next/font/google";
import ReactQueryProvider from "@/lib/ReactQueryProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Bir Academy",
  // description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <EmotionCSSRegistry>
            <ReactQueryProvider>
                {children}
            </ReactQueryProvider>
        </EmotionCSSRegistry>
      </body>
    </html>
  );
}
